[workspace]
members = ["dns", "server"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
resolve-dns = { path="dns", version="0.1.0" }
resolve-server = { path="server", version="0.1.0" }