[package]
name = "resolve-dns"
version.workspace = true

[lib]
name = "resolve_dns"
path = "src/lib.rs"

[dependencies]
rand = "0.8.5"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"

