[package]
name = "resolve-dns"
version.workspace = true

[lib]
name = "resolve_dns"
path = "src/lib.rs"

[dependencies]
clap = { version = "4.3.2", features = ["derive"] }
rand = "0.8.5"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
serde_yaml = "0.9.21"

